### ISSUE TITLE
Disable Melee Toggle on Saber Weapons

### ISSUE THREAD

**Issue by DarthFutuza** [JKGDevs/JediKnightGalaxies#108]
If the player turns off their saber using aci, it puts the player into melee mode for the rest of the weapons.  This should not happen, should have a check to see if its a saber weapon assigned to that aci slot, if so, just turn the saber off, but don't change toggle for melee/gun.

eg: Turn saber off, then switch to gun, you are now in melee (do not want).

Boothand mentioned this.

**Comment by eezstreet** [comment]
Further thoughts? Might mark this as closed if there's nothing further to discuss.

**Comment by DarthFutuza** [comment]
Yeah I'll go ahead and close it, it's such a minor thing anyway.
