### ISSUE TITLE
Stun is somewhat Derpy

### ISSUE THREAD

**Issue by DarthFutuza** [JKGDevs/JediKnightGalaxies#112]
Basically at the present it just freezes the player.  This can result in some interesting scenario's, like when rolling (animation has a chance of glitching and getting stuck in a loop from 1st person view, until stun has expired).  Also can freeze people in mid-air and save them from falling or jumping at you.  You can also reload while stunning.  And maybe even do more cool stuff.  (I know its not finished, just saying).

**Comment by eezstreet** [comment]
Rolled into issue #124
