### ISSUE TITLE
Stop Drop & Roll

### ISSUE THREAD

**Issue by DarthFutuza** [JKGDevs/JediKnightGalaxies#113]
Putting out fires with roll seems to take a little too long, takes about 3-4 rolls.  I'd say do it in 1 or 2.

**Comment by DarthFutuza** [comment]
Realized that the code for this is a 50% chance of putting out.  Maybe increase chance by 10% with each successive roll?  If no one wants that then that's cool, just close the issue.

**Comment by Silverfang22** [comment]
Possibly make it so that the longer you are on fire the easier it is to put out by rolling?

**Comment by DarthFutuza** [comment]
I'm going to close this for now because after play testing it a bunch, I think its fair.  By the time you'd roll more than twice the fire effect is out anyway.
