### ISSUE TITLE
Couple Weapons have equip/unequip issues

### ISSUE THREAD

**Issue by DarthFutuza** [JKGDevs/JediKnightGalaxies#117]
There appear to be a few weapons that when equipped, keep switching between equipped and unequipped making them unusable.

Known:
pistol_de-10 snub
Occasionally plasma grenade

**Comment by eezstreet** [comment]
Cannot reproduce.

**Comment by Wayward1** [comment]
I can reproduce this with the current release

**Comment by DarthFutuza** [comment]
The bug is caused by bad .wpn files usually.  You might have some left over files from a previous install causing it possibly, though I also don't think eezstreet has uploaded the latest assset5.pk3 yet either.

**Comment by Wayward1** [comment]
Ah, ok. It may be the latter, because this is my first install.
