### ISSUE TITLE
Server browser shows non-JKG servers with JKG-only filter on

### ISSUE THREAD

**Issue by gerbilOFdoom** [JKGDevs/JediKnightGalaxies#118]
Happening as of latest commit. Tried reverting 1e0fff7 but found the issue persists even after cycling game modes. This occurs in the FFA game mode only, as far as I can tell. Switching to Faction Battle shows the JKG dev server.

**Comment by DarthFutuza** [comment]
Working as intended?  Or should we take out other menu options so that ffa and other game modes are not available?

**Comment by eezstreet** [comment]
Fixed.
