### ISSUE TITLE
Damage Types

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#124]
Give the ability to make certain weapons deal extra or less damage based on their damage type and what type of target they're hitting, ties in with armor and shield system

More details http://jkhub.org/topic/6658-concept-damage-types/

**Comment by eezstreet** [comment]
Done. They're tied to what MOD_ you're using, and in a new meansOfDamage.json to tie it all together. MOD_BLASTER for instance is now a blaster type weapon, and MOD_ACP is an ACP type weapon. They all do different damage based on what they hit, but resistances aren't in yet.
