### ISSUE TITLE
Shield System

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#125]
Make shield items for player's inventory, only one can be equipped at a time. When equipped make player's shields regenerate over time to their maximum value

4 Main Stats:
Maximum Shield Value
Recharge Rate
Recharge Delay
Depleted Recharge Delay

**Comment by DarthFutuza** [comment]
Details here: http://jkhub.org/topic/6813-concept-shields/

**Comment by eezstreet** [comment]
Working in Develop branch.
