### ISSUE TITLE
Extreme Audio Distortion with grenades (game-breaking)

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#129]
Certain Grenades seem to have their "warning beeps" extremely high pitch when they're within a couple feet of the player, the closer they are the higher the frequency.

This also seems to cause the game to crash completely.

I have noted this with the C-22 Fragmentation Grenade and Cave Johnson's Lemons (Pretty funny to hear "squeaky voice" Johnson if it didn't potentially crash the game and cause ear-bleeding distortion)

**Comment by DarthFutuza** [comment]
When testing this myself, I never noticed it.  Silverfang as my witness.  Tried both c-22 and Johnson Lemons, probably happens only during certain conditions or possibly with certain cfgs.

**Comment by eezstreet** [comment]
Value of s_UseOpenAL? s_doppler?

**Comment by DarthFutuza** [comment]
Can't reproduce.  Closing.
