### ISSUE TITLE
Adjust weapon balance

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#133]
Noted weapons:
LS-180: too inaccurate
LT-60: Too strong for low-cost weapon (adjust price or nerf)
DE-10 (snub): Needs more recoil, this thing packs a punch!
Cryoban Grenade: Requires damage type adjustment, needs code... Take away freeze and just have damage over time until then?
Proximity Mines: Needs code adjustment, perhaps nerf damage..? Then again smoke grenades are a hard counter if you know where to find them.
Starting Pistol: Too boring of a weapon in my opinion, up the fire rate a little, potentially do a visual update ...use as testbed for animated .glm first person model?

Weapons that need to be removed from shop:
All lightsabers: Too WIP and too cheap to be available in current implementation
Carbonite rifle: Oh man, getting flashback nightmares of how OP this thing is
Lemons!: Easter egg weapon, fun but shouldn't be available in normal gameplay
Sterling L2A3 submachine gun: Easter egg weapon, see above
T-21, T-21 w/ Bipod: These were disabled for a reason, not sure why they got reenabled, NPC weapon only for now. (Visual update in dev files? Need to relook at that blender file).

**Comment by DarthFutuza** [comment]
I think having lightsabers in are fine, as they need more testing and we should expose them to players more.  They're functional enough that I don't mind some of the bugs being public.  Sure players can just give themselves sabers with cheats, but figuring how to do that may not be immediately obvious.  At least for now.

**Comment by eezstreet** [comment]
What would you like the starting pistol to be? I can change it very quick/easily.

**Comment by DarthFutuza** [comment]
The naboo one with 5 clips before it needs a reload is probably a good one.

**Comment by Silverfang22** [comment]
Actually I changed the DL-18 to a point where I think it's fine as a starting weapon, it just fired too slow before

**Comment by DarthFutuza** [comment]
I'm closing this for now as most of the issues are no longer relevant/need to be re-evaluated with all the code rewrites and balance changes.
