### ISSUE TITLE
Sort shop by price

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#137]
Cheap items at the top, expensive items at the bottom

**Comment by DarthFutuza** [comment]
We can also sort alphabetically too or by weapon type?

**Comment by Silverfang22** [comment]
Would be nice to have tickboxes on the sides as filters to limit between blasters, consumables, etc. plus a search bar would be nice to have eventually as well, currently though I think sorting by price is fine.

**Comment by eezstreet** [comment]
Implemented via new shop menu.
