### ISSUE TITLE
"Press E to pick up weapon" get stuck on screen

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#142]
When looking at a weapon that is placed on the map (not dropped etc.) the message that shows up on your HUD is permanently stuck on your screen

**Comment by DarthFutuza** [comment]
It goes away if you do something else like press esc or (I think) firing your weapon.

**Comment by DarthFutuza** [comment]
Is this still happening?  I've never had it happen to me.

**Comment by ensiform** [comment]
Always happens
