### ISSUE TITLE
Certain effects orient towards the origin

### ISSUE THREAD

**Issue by eezstreet** [JKGDevs/JediKnightGalaxies#166]
Some effects, such as the starting pistol's stun charge laser, seem to point towards the origin at all times. This needs to be investigated further.

**Comment by Silverfang22** [comment]
Also ARC Caster Mk.1 hit effect causes smoke to appear at the origin

**Comment by Silverfang22** [comment]
Bumping this up to high priority, this bug results in invisible flames (flame and smoke effects appear at origin) this can result in players getting hurt from something they can't see.

This applies to the fire effects that are bolted to players as well, so other than sizzling and taking damage it's not easy to tell you're on fire.

**Comment by DarthFutuza** [comment]
Which weapon is giving you invisible flames?  For example if I chuck a plasma grenade and walk into it, I can definitely tell I'm on fire, is it just when taking damage from a flamethrower aimed at you by someone else or something?

**Comment by eezstreet** [comment]
I think I've found the problem, and it's not where I expected it to come from.

In short, the problem is because the cgame and engine shared memory pointers are getting out of sync. This can happen when cl.mSharedMemory gets modified but cg.sharedBuffer.raw isn't, or vice versa.

It seems that cl.mSharedMemory is getting overwrited from a MSG_ReadBits call being done on the entityState. So the entityState fields are probably wrong somewhere. I need to review it and see what's going on.

**Comment by eezstreet** [comment]
This is possibly fixed via c95b9f86295716d3e466b57b7f4fca54212e8630 - need further testing to verify that it's fixed.
