### ISSUE TITLE
Stamina consumption for jumping/rolling

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#170]
Make jumping and rolling use stamina, as with sprinting prevent jumping and rolling when below a certain amount of stamina.

**Comment by eezstreet** [comment]
How much stamina should be consumed for jumping/rolling though?

**Comment by Silverfang22** [comment]
I think 15 is a good value for both for now, prevent either action under 20 (sprinting is prevented under 10)

**Comment by Silverfang22** [comment]
I'm also thinking there should be a small buffer time where you can't jump after landing, something very small just to allow the "landing" animation to play.

**Comment by DarthFutuza** [comment]
I think only 2-5 should be consumed for jumping/rolling or less.  Don't want to punish it to much, just a little bit is enough.
