### ISSUE TITLE
Aim Down Sights Improvements/Bugs

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#172]
Make it so that the gun tilting when looking straight up and down does not occur when aiming down sights

Reduce or remove gun sway (or change to no rotation, just translation) when walking and aiming down sights

Possibly make it so that the gun fov itself is modified when aiming down sights (to make some iron sights more apparent)

**Comment by eezstreet** [comment]
FOV can already be modified from ironsights without further code changes.

**Comment by eezstreet** [comment]
Corrected in above listed commit, except for the FOV which is controlled per .wpn file. 

Tilt uses an exponential approach instead of hard thresholds to trigger its effect.
