### ISSUE TITLE
Killfeed shows players killed themselves

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#178]
Related to ^xRGB code

**Comment by DarthFutuza** [comment]
Can you clarify so I can look at it?

Is this like player types in /kill and it says they killed themselves or something clearly broken like they darthfutuza kills eezstreet, but it instead reports that darthfutuza killed darthfutuza?

**Comment by eezstreet** [comment]
Fixed with new color code stuff done by @ensiform and myself.
