### ISSUE TITLE
Maps that have their own starter weapon change cvar globally

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#180]
After loading JKG_Taris, which has the starter weapon set to rifle_dressy, the cvar jkg_startingGun is now set to "rifle_dressy".

**Comment by Silverfang22** [comment]
Oddly enough this also seems to set it to the default? http://i.imgur.com/YrYv7pK.jpg

**Comment by eezstreet** [comment]
Does this cause any discernable game effects?

**Comment by DarthFutuza** [comment]
@eezstreet other then changing the starting weapon for the next weapon, no? eg: load jkg_taris, changes starting weapon to dressy, then load jkg_ctf_bespin and starting weapon is now dressy instead of the pistol it ought to be.

**Comment by DarthFutuza** [comment]
Also, you can set this to something invalid like jkg_startingGun = "blahblahblah".  Should probably put a check in after weapons load to ensure jkg_startingGun is set to a valid weapon and if not set it back to default.

**Comment by ensiform** [comment]
This is an issue with ***archived*** cvars being set by maps in general.  Including gravity, though I don't think gravity is actually archived.

**Comment by ensiform** [comment]
Doesn't seem to be fixed exactly as intended yet.

**Comment by DarthFutuza** [comment]
I can't get this to happen anymore, I believe this was fixed.
