### ISSUE TITLE
Linux server crashes when changing maps

### ISSUE THREAD

**Issue by eezstreet** [JKGDevs/JediKnightGalaxies#182]
Need to investigate this ASAP.

**Comment by ensiform** [comment]
I couldn't reproduce any issues on Debug build currently.

Maybe someone or I can at another time check with RelWithDebInfo build.

**Comment by AlexCSilva** [comment]
I didn't think to start  an issue like this. Also I think for windows build, I'm not sure if it is map_restart. However, when a round ends and you ready up it seems to crash instead of restarting the map. (Have map cycle turned off for the moment on my server).

**Comment by eezstreet** [comment]
No sign that the Windows issue is related to the Linux one as of yet.

**Comment by ensiform** [comment]
@eezstreet what makes you say that?

**Comment by eezstreet** [comment]
Windows Dedicated server crash happens when you close out with the X button and only that - `map_restart` and `quit` don't trigger the crash. The Windows dedicated server crash is because the game module gets `G_ShutdownGame` called and an extra frame is getting through. I'm not sure why yet.

**Comment by ensiform** [comment]
The x button calls "quit" which calls killserver soo....

**Comment by eezstreet** [comment]
@AlexCSilva @ooxavenue give it a whirl and see if it causes issues

**Comment by AlexCSilva** [comment]
Changing maps still crashes though i might not have latest assets, just builded server and jampgame

**Comment by ensiform** [comment]
No it doesn't. Its th exact same crash.  Update your builds properly.

**Comment by AlexCSilva** [comment]
Okay it works now, from making a 64bit build on the same vps that runs server. Can probably close this issue for now.

**Comment by AlexCSilva** [comment]
It seems to crash again but only when changing to a different map. Doing map_restart or simply changing to same map by /map or /devmap doesn't crash though. From doing some more testing, it appears it doesn't crash at all when changing maps if no one is connected.

**Comment by ensiform** [comment]
Pretty sure its a different issue entirely.  Or maybe yours was also a combination of more than 1 all along.

**Comment by AlexCSilva** [comment]
Yeah maybe
