### ISSUE TITLE
Viewmodel Momentum

### ISSUE THREAD

**Issue by eezstreet** [JKGDevs/JediKnightGalaxies#184]
JA++ has a feature called viewmodel momentum. Basically when you move the camera quickly it moves the gun in first person as well. Might make guns look more snappy/responsive. 

Relevant chunk of code:
https://github.com/Razish/japp/blob/master/cgame/cg_weapons.cpp#L181-L202

Worth looking into?

**Comment by DarthFutuza** [comment]
If you think it would be pretty easy to add, sure, provided Razish is cool with it.
