### ISSUE TITLE
Fix Maps

### ISSUE THREAD

**Issue by DarthFutuza** [JKGDevs/JediKnightGalaxies#185]
Some maps have broken vendors which attack players instead of standing around.  eg: jkg_spaceport (Hutt players will be attacked).

Maps ready for play:
jkg_ctf_bespin
jkg_coruscant_lower
jkg_nightfall

**Comment by DarthFutuza** [comment]
Maps are mostly fixed.  I'm an idiot.
However, vendors are incorrect on:
 jkg_spaceport (Vendor is hostile to Hutt players).
jkg_taris (hostile to blue team)

**Comment by eezstreet** [comment]
Not a code issue.
