### ISSUE TITLE
Windows Dedicated Server crash

### ISSUE THREAD

**Issue by eezstreet** [JKGDevs/JediKnightGalaxies#187]
Crashing upon closing the dedicated server using the X (close) button. Doesn't seem to happen upon quit.

**Comment by eezstreet** [comment]
Upstream issue in OpenJK. See more: https://github.com/JACoders/OpenJK/issues/887

It's a complicated issue to fix, but basically the issue arises because the signal handler is killing the game from a separate thread, which can cause crashes if the main thread is in the middle of a gamecode frame.
Marking as low priority as people can still close the game without crashing using "quit" or "killserver" commands.
Moved to Unknown Milestone until an OpenJK fix is established.

**Comment by DarthFutuza** [comment]
I just tested this and it doesn't seem to be crashing anymore when you do this.  Tried on Windows 10, with v1.3.23 (alpha) on 8/9/2022.

OpenJK didn't end up fixing the issue and closed it out since it also apparently isn't a problem anymore.  https://github.com/JACoders/OpenJK/issues/887
