### ISSUE TITLE
Make guns that are aimed down sights move slightly (but not tilt/sway)

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#188]
Make them move a little bit on the Y and Z axis, and a very small amount of the X axis while walking.

Sights should still be usable, but no movement at all looks a little unnatural when moving.

**Comment by eezstreet** [comment]
How about 75% reduced bobbing?

**Comment by DarthFutuza** [comment]
Reduced?  Wasn't he asking for more movement?

**Comment by eezstreet** [comment]
There was originally a lot of movement, and it was asked to remove the bobbing in ADS, which doesn't look great, so I'm asking if 0.25 * the original movement would be good? In my tests it seems to look OK.

________________________________

**Comment by DarthFutuza** [comment]
Sound acceptable, we'll have to try it to see.  Have you pushed the changes to master yet?

**Comment by Silverfang22** [comment]
The point is not to have any rotation, only translation

**Comment by eezstreet** [comment]
The newest version of the binaries has three new cvars: jkg_sightsBobX, jkg_sightsBobY, and jkg_sightsBobZ. Whenever you get the chance, give me a default value for these and I'll implement it.
