### ISSUE TITLE
Improvements to Vendors

### ISSUE THREAD

**Issue by DarthFutuza** [JKGDevs/JediKnightGalaxies#189]
Notes: Most of these changes can probably changed via the lua functions around vendors, though some may need to be AI changes.

Vendors should not be usable by the enemy team.  If you attempt to use an enemy vendor, it should respond with a rejection sound and do nothing. eg: "We've got an intruder here, help!"  "No, no!  Stay away!"  In addition they should not attack npcs or players on the opposing team, just sit still and sell stuff.

Whatever team an npc is assigned to be the vendor for should override it's default npc settings.  eg: If you put Luke Skywalker as the Imperial team vendor, he shouldn't try to attack imperials anymore, but shut up and sell stuff to them.

Neutral vendors can be accessed by either team and offer higher more expensive quality items usually.  Neutral vendors should either wander the map or be located in a central location in neutral territory.  The idea is that neutral vendors are a bit like the blackmarket dealer of the match and buying from them is risky (you could just get shot by the other team while doing so).  It would also be cool if they didn't appear until mid match (eg: they spawn 10 minutes in or something), or they just simply have nothing for sale until mid match and later.

If vendors do move (most cases they probably shouldn't), they should probably have a set path or allowed area, so they don't walk off the edge of the map or something and kill themselves.

I don't really like vendors being ents in a map, means we have to distribute new map (at least to server hosts) every time we want to make changes to vendors.  Need to be easier to modify.

Vendors should also probably not be affected by knockback as they currently are.

**Comment by eezstreet** [comment]
This needs to be split up into multiple issues. Having large conglomerate issues with multiple things in them makes it harder to assign them into milestones.
