### ISSUE TITLE
Firing animation no longer loops correctly

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#193]
When firing a fully automatic weapon or quickly firing a semi-automatic weapon, it will only play the firing animation once, after that it seems to sit on one frame and never loop.

**Comment by eezstreet** [comment]
This commit broke it and was reverted, fixing the issue:
https://github.com/JKGDevs/JediKnightGalaxies/commit/e226818a96092ad026e1d04423dd254250a42d3e
