### ISSUE TITLE
Login to Admin Not Working

### ISSUE THREAD

**Issue by DarthFutuza** [JKGDevs/JediKnightGalaxies#198]
/login doesn't work says "unknown command"

**Comment by AlexCSilva** [comment]
probably an easy fix but not sure

**Comment by ensiform** [comment]
Sounds like you don't have the glua or server folders which aren't in assets5 anymore.

**Comment by AlexCSilva** [comment]
The folders are bundled with the serverside zip and r on my server but not working. Eezstreet said it might be something to do with something that Silverfang changed

**Comment by eezstreet** [comment]
It's actually fixed if you delete the glua file from assets and copy it over from the codebase. It seems something went wrong when packing the files up.

**Comment by DarthFutuza** [comment]
Want to fix it and release as 1.2.1? Or wait till after scrimmage match?

**Comment by AlexCSilva** [comment]
I can just fix it on my server for now
