### ISSUE TITLE
Grenades Don't Start With Ammo

### ISSUE THREAD

**Issue by DarthFutuza** [JKGDevs/JediKnightGalaxies#199]
When you first buy a grenade type item (tripmines, stun grenades, thermal detonators, etc.), you will get 0 ammo and have to respawn before you get ammo for the grenade.  This is also partially a balance issue since it deters players from buying grenades when they otherwise wouldn't.

**Comment by Silverfang22** [comment]
This will be fixed when grenades are made to be consumables.

**Comment by eezstreet** [comment]
Grenades now function similarly to consumables in branch develop, so this issue can be closed.
