### ISSUE TITLE
Investigate slowly moving backwards while ADS + fast walk/roll backwards when walking.

### ISSUE THREAD

**Issue by Pande** [JKGDevs/JediKnightGalaxies#20]
And other strange behaviour when walking. Likely tied into the speed modifier stuff.

**Comment by eezstreet** [comment]
The speed modifier was not being added correctly in all the right places - chalk this one up to the speed being modified in so many different places. It should be correct, although the change combined with the lack of bob/sway in ADS will be unsettling at first.
