### ISSUE TITLE
Ammo as items

### ISSUE THREAD

**Issue by eezstreet** [JKGDevs/JediKnightGalaxies#200]
Ammo should be considered as items with quantity. The framework exists for items with quantity, but ammo is treated specially currently.

**Comment by eezstreet** [comment]
There needs to be some change in how we handle this.

Honestly the way we have ammo right now is fine, but there's no special ammo types implemented yet. That's the problem, I think. I don't think having ammo as items is going to add anything to the gameplay, but we should focus instead on adding the ability to switch ammo types.

I don't know - thoughts?

**Comment by DarthFutuza** [comment]
Agreed, however, something also needs to be done about resupplying ammo stocks through the vendor or through another means (eg: Ammo vending machine).

**Comment by eezstreet** [comment]
HAYO. There's now ammo as items.
The catch is that they aren't "truly" items...they're "ammo pack" items that instantly dissolve once they appear in the player's inventory. You can buy them from vendors.

**Comment by DarthFutuza** [comment]
Thinking we might want them to show up in inventory as ammo pools/packs (since later on we may want to allow them to be lootable/tradeable to other players).
