### ISSUE TITLE
Crash from invalid voting choices

### ISSUE THREAD

**Issue by AlexCSilva** [JKGDevs/JediKnightGalaxies#203]
Darth Futuza and others managed to crash server but picking invalid choices or something of the likes when voting. Someone voting for CTF mode would also crash the server but it at least it exits properly so server can restart.

Example of crash:
ClientConnect: 0 [81.183.117.227:29070] (D7B4AA6DFF2FEA61D31DB5505DCAE76D) "^7"
broadcast: print "Mysterious Soldier^7 @@@PLCONNECT\n"
Sending heartbeat to masterjk3.ravensoft.com
Sending heartbeat to master.jkhub.org
ClientBegin: 0
G_WriteSessionData: writing session/meta.json...Writing session file session/client00.json
done
variable change -- restarting.

**Comment by eezstreet** [comment]
There's no logical reason that voting for gametypes would cause a crash. I think it's something else going on, like the server crashing upon restart...which might have already been fixed with assist changes. Marking as potentially fixed for right now.

**Comment by DarthFutuza** [comment]
Can't get this to happen anymore.  Closing the issue out.  Reopen it if it comes back up.
