### ISSUE TITLE
Adjust treasure classes and item prices for better overall feel.

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#205]
There are a lot of cheap, but not terribly useful items, a couple of almost rediculously power-per-credit-spent items, such as the LT-60 series and not a lot of items in the same price range as them.

Overall I will likely lower the costs of some 1200-1500 credit cost items and possibly raise the prices of the LT-60s by a small amount... possibly figure out some sort of alternative weapon to them.

There aren't a lot of cheap fully automatic weapons besides the LT-60, I may make the advanced Trandoshan pistol fully automatic.

**Comment by DarthFutuza** [comment]
Make cheaper weapons ammo more expensive for more balance.  (Cost a fortune to fire it).

**Comment by eezstreet** [comment]
There should be an option coded in the treasure class file to make items picked within a subclass to be unique. So for instance this could make it ONLY pick one LT-60 type or ONLY one E-11 rifle.

**Comment by DarthFutuza** [comment]
Discussed possibly having a decay over time feature, where a treasure group/class will decrease it's picks over time (eg: -1 every 5 minutes).  This way basic items (crappy pistols and stuff) needed in the beginning of the game become rarer towards the end of the game.  Note: Might be a bad idea for players joining late, unless we have a credit balance system (give them welfare, etc)

**Comment by DarthFutuza** [comment]
Closing this out, things have been adjusted a lot since then.  I'm sure we'll have more balance issues in the future from patch to patch, but we can open a new issue when those crop up.
