### ISSUE TITLE
^1ERROR: Couldn't load ambient sound sets from sound/sound.txt

### ISSUE THREAD

**Issue by Wayward1** [JKGDevs/JediKnightGalaxies#207]
I get this error when I try to join the public test server with the new update, running Windows 10 x64. I followed the update instructions to copy the new jkgalaxies folder over the old one. I can provide the full crashlog if necessary.

**Comment by eezstreet** [comment]
If you did this, the installation instructions weren't followed correctly. Try installing it via https://jkhub.org/files/file/3116-jedi-knight-galaxies-clientside/ - drop the jkgalaxies into Gamedata and run via the .bat.

**Comment by Wayward1** [comment]
I apologize for the false issue, it seems I had a momentary lapse of concentration and was following the old update instructions >.<
