### ISSUE TITLE
Crash without error when starting map from terminal

### ISSUE THREAD

**Issue by Wayward1** [JKGDevs/JediKnightGalaxies#208]
Using Windows 10 x64, latest update, when I try to start a map from the terminal it crashes almost instantly without an error. It worked fine with the previous version.

**Comment by eezstreet** [comment]
Please don't make multiple issues.

**Comment by Wayward1** [comment]
Again, I apologize for the false issue, but given the circumstances it seemed like a different problem deserving a separate issue.
