### ISSUE TITLE
Tempfix: Stuns

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#218]
Prevent stunned player from shooting, but do not prevent them from moving

**Comment by DaloLorn** [comment]
Honestly, I'd go the other route - IIRC, someone around here suggested physically knocking them down and forcing some kind of special getup animation, like a real (and stupidly short-lived, but that can't be helped :P) stun.

Shields will block stuns, according to what you've said, and various other things could reduce their effectiveness, but aside from the firing rate thing drastically boosting its 1v1 potential, I think that it's more or less fine the way it is - you pay *a large portion* of your current clip to produce a much larger and clumsier projectile (notice how I never managed to stun you while I was hiding behind those crates) which either buys time for you to escape or lets your teammates take the enemy down.

The latter part also encourages heavier use of cover and gives grenades a nice purpose - you and Mandalore were perhaps a bit too eager to rush at our barricades without softening us up with explosives first. (On a related note, I still think stun grenades are simultaneously underpowered and overpowered - I've been tossing C-14As and Lumas en masse over the past several days, but the only thing I accomplish is badly injuring my targets if I throw the grenades right. It never leaves an opening for me to rush in and blast them.)

**Comment by Silverfang22** [comment]
Yes that was me that suggested knockdown and stagger, stun just currently does not work the way it's intended to work. Grenades in 1.3 will be consumables, so the matter of having 4 of them every time you spawn isn't an issue anymore (if you really wanted to do this, it would be a massive credit sink).

As for blinding targets or otherwise causing some sort of advantage in-combat I've already opened an issue for that, currently all blind is done via efx (as far as I know). Stun grenades should also probably cause a slow (and later, knockdown/stagger just like other stuns).

**Comment by eezstreet** [comment]
I think this is something which warrants more discussion within the context of the new changes to buffs and weapons and how they interact with each other. I'm marking this as closed for right now.
