### ISSUE TITLE
Passive Healing

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#220]
Reduce delay it takes before passive healing kicks in, reduce amount of healing gained per second (0.5 hp/s), increase healing gained per second over time, maximum of 5 hp/s

**Comment by DarthFutuza** [comment]
Do you know how long the delay currently is?  Why have increased healing rate over time (just want to know your reasoning for that)?

**Comment by Silverfang22** [comment]
because the delay shouldn't be super long (maybe 20-30 seconds), but you shouldn't immediately heal your entire healthbar if someone is chasing you but doesn't manage to catch you right away.

Players should still be able to capitalize on strong players being weakened, but right now the passive healing might as well be non-existant

**Comment by Pande** [comment]
Also have we considered running back into your own base just to Regen? The
more the gameplay advances the more I hate having bases. I think we should
experiment with the counter strike method and see how it plays out. Maybe
tie it to location so you can't use it elsewhere in the map.

**Comment by DarthFutuza** [comment]
Had a look at this.  This almost isn't necessary anymore with healing items available from vendors such as bacta.  If you're hurt, go buy items to heal.  The only problem is that they aren't guaranteed to spawn from the normal generic vendors.  That said, there is a specific medical vendor that is guaranteed to sell at least two types of bacta, so if mappers wanted to add one of those to each teams base it will basically fix this.

Aside from that there are a number of cvars to be aware of:
jkg_healthRegen, default: "1",			
jkg_healthRegenDelay, default: "60000",		
jkg_healthRegenSpeed, default: "2500"

jkg_healthRegen enables/disables regen.  jkg_healthRegenDelay is how many milliseconds to wait before regen kicks in after taking damage (so just setting that to 25000 will probably fix most complaints here).  jkg_healthRegenSpeed is the rate at which you gain hp when regen activates (so here every 2.5 seconds you'll get 1 hp).  While I could change the default values in the code, its a cvar so you can try them out yourselves and let me know what the best defaults would be after experimenting with it.  I'll close this out after we change the default values to something better as 60 seconds is too long.

**Comment by DarthFutuza** [comment]
I found that 25 seconds (25000) and 1500 for regen speed works out very nicely.

**Comment by DarthFutuza** [comment]
I don't think this an issue anymore, just change the cvar if you want faster healing.
