### ISSUE TITLE
Unassigning a weapon from ACI while it is equipped

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#224]
If you unassign a weapon while you currently have it equipped, at least in my experience, it will give you a DC-15A with no ammo or firemodes.

**Comment by DarthFutuza** [comment]
Also experienced this once, had a bit of a hard time repeating it though.

**Comment by DarthFutuza** [comment]
Tested it, wasn't able to reproduce.  I believe it is fixed.  Reopen this if someone gets it to happen again.
