### ISSUE TITLE
Death animations go to last frame instantly

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#225]
Still investigating...

When I kill someone else their death animation seems to play at an absurdly high FPS or at least go to the last frame of animation instantly.

Not reproducible with /kill! Death animation plays normally.

**Comment by eezstreet** [comment]
Is this still happening on later versions?

**Comment by DarthFutuza** [comment]
Don't think so.  I haven't noticed it.  @Silverfang22 ?

**Comment by Silverfang22** [comment]
Should be fixed, closing.
