### ISSUE TITLE
Chat messages occasionally do not appear in chatbox

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#226]
When sending a message I've noticed that sometimes the rest of the chat will move like it sent, however it will not appear in the chatbox at any point or act like it otherwise exists (there won't be a "blank" line). It will however appear in the console.

**Comment by DarthFutuza** [comment]
Messages will also overflow the chatbox while typing.  Something funky going on with chatbox boundaries most likely.

**Comment by eezstreet** [comment]
This seems to be caused by really long messages but it happens fairly inconsistently.

**Comment by Silverfang22** [comment]
Still haven't gotten it to happen consistently, but I've eliminated some possibilities:

It happens with short names and long names
It happens with names with color codes and without
It happens with short or long messages

**Comment by eezstreet** [comment]
Fixed. There was some old code which was using 11 lines when the chatbox really supported 12 lines.

**Comment by DarthFutuza** [comment]
YES!  Nice.
