### ISSUE TITLE
Starting weapon cannot be reloaded after dying

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#227]
Still investigating...

Whenever you /kill the starter weapon will have 0/0 ammo, however /myammo still shows 400/400 of its ammo type, unknown what "fixes" it ingame, but I have had it where I was later able to reload it.

**Comment by eezstreet** [comment]
Can't seem to reproduce it. Is there some way to trigger it?

**Comment by Silverfang22** [comment]
This was consistently happening to Smoo and myself during playtest. In my experience it would always occur after your first death (at least with /kill). I will do some more investigation.
