### ISSUE TITLE
Equipping a shield to slot 0 in ACI crashes client

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#229]
I swear I was able to equip to slot 0 before, but it seems to happen on a consistent basis with any shield.

Happens regardless of whether or not you have starter weapon in slot 0 or not.

**Comment by DarthFutuza** [comment]
Repeatable with: give item shield_golan_ds1, then assign to slot 0, will crash client.  If you auto equip it will also usually happen to, because it tries to assign it to slot 0.  However, some other shields will not crash such as the shield_golan_ds2 afaik.

**Comment by eezstreet** [comment]
This is fixed as of 809cff4.
