### ISSUE TITLE
Armor looks glitched

### ISSUE THREAD

**Issue by eezstreet** [JKGDevs/JediKnightGalaxies#231]
When respawning, the armor looks like your corpse.

**Comment by DarthFutuza** [comment]
![armor bug](https://cdn.discordapp.com/attachments/152168677578506240/390026309994020874/shot2017-12-11_23-16-22.jpg) Seems to happen after equipping armor, dying and then respawning.  Doesn't happen the first time.

**Comment by DarthFutuza** [comment]
If only a piece of armor is equipped (eg: the helmet_stormtrooper) upon death only that piece of armor ends up in the dead animation state.  The player model section where the armor was is left empty without anything being drawn where the armor used to be, while the armor is left on the ground in the dead position  If it is unequipped or destroyed, it doesn't go away.  If you unequip it before dying, when you respawn it will still appear on the ground, however, if you reequip it it will go back in place where it should be off of the ground.  (To other clients it may appear as if they still have the armor on or as normal as if they had never equipped armor - haven't figured out a clear pattern yet, might be only on the first time?)

**Comment by eezstreet** [comment]
I think the armor equip state as networked to other clients is related to the jetpack not being visible sometimes to other clients. It's to do with non-networked GHOUL2 instances.

**Comment by eezstreet** [comment]
The issue should now be fixed as of the most recent commit.
