### ISSUE TITLE
Animation freezes after being kicked

### ISSUE THREAD

**Issue by DarthFutuza** [JKGDevs/JediKnightGalaxies#237]
1st Person:
![frozen first person](https://i.imgur.com/aPFyIFo.jpg)

3rd Person:
![frozen 3rd person](https://i.imgur.com/97Cw8WY.jpg)

If another player kicks you, after getting up your animation will freeze and you'll be unable to move or aim.  However, you can get out of the "freeze" by switching to melee and then performing a kick.  This will resume the animation and unstick you.  While in this frozen state, collisions do not work properly and you cannot be kicked by other players (can still be punched and shot though).

**Comment by eezstreet** [comment]
Can't seem to duplicate this.

**Comment by Silverfang22** [comment]
Repeatable with knockmedown

**Comment by eezstreet** [comment]
Possibly fixed. Need verification (not with knockmedown)

**Comment by DarthFutuza** [comment]
Tested it and it appears to be fixed.
