### ISSUE TITLE
Some Weapon Ammo Text Too Long

### ISSUE THREAD

**Issue by DarthFutuza** [JKGDevs/JediKnightGalaxies#238]
Some weapon ammo text does not fit within the ui boundaries and is cut off:
![cut off text](https://i.imgur.com/jM6FhsF.jpg)  This is made worse by smaller resolutions, but still happens even on large resolutions such as 1080p.

For those with long names we should consider
1) Shorter version / shorthand
2) A code fix that will provide scrolling text (goes left to right then back again slowly displaying the whole text).

**Comment by eezstreet** [comment]
We need to think of a way to make this look good. Scrolling text is a bit distracting I think. Maybe list the ammo type to the left (or maybe use icons?)

**Comment by DarthFutuza** [comment]
Even a newline between ammo amounts and ammo type would help a lot.  I think scrolling text is fine as long as it is infrequent. Especially if it only happens on poorly named ammo types (eg: ones with like 7+ character names), because we can definitely shorten most of them to shorthand stuff I think.

**Comment by eezstreet** [comment]
Would that maybe make the ammo text too small, though?

**Comment by eezstreet** [comment]
This is resolved. Ammo type now displays above the firing mode.
