### ISSUE TITLE
Armor animation isn't updated by "looking at object of interest"

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#244]
Helmets aren't affected by the code that makes your head turn to look at nearby players.

**Comment by Silverfang22** [comment]
This applies to looking up and down as well.

**Comment by eezstreet** [comment]
Need to verify if this is still an issue, after the most recent changes to the code.

**Comment by eezstreet** [comment]
Either I can't replicate this, or it's fixed.
