### ISSUE TITLE
Scoped weapons do not set the player to "walk" animations when aiming

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#245]
When scoped in your player appears to be running on a treadmill, yikes!

**Comment by eezstreet** [comment]
Should be a .wpn change.

________________________________

**Comment by eezstreet** [comment]
Is there a list of weapons which this is an issue for?

**Comment by Silverfang22** [comment]
.wpn files do not include animation fields for walking or running, it's all scoped weapons as far as I know
