### ISSUE TITLE
Bleed effect lights players on fire

### ISSUE THREAD

**Issue by eezstreet** [JKGDevs/JediKnightGalaxies#248]
Title. Reported by Darth Futuza.

**Comment by DarthFutuza** [comment]
It actually does bleed damage, just uses the fire effect while the debuff is active.  Was this a place holder perhaps?

**Comment by DarthFutuza** [comment]
Happens with more than one buff.  To the client the fire effect does not appear, however to other clients you will appear to be on fire if you have a debuff active (and they will appear to be on fire to you if they have an active debuff).  Seems to happen for all debuffs.
