### ISSUE TITLE
Disintegration does not seem to function.

### ISSUE THREAD

**Issue by eezstreet** [JKGDevs/JediKnightGalaxies#250]
Thermal detonators do not seem to cause disintegration, despite their damage type (MOD_DISRUPTOR) being flagged as such. It's likely this extends to other weapons using this damage type.

**Comment by Silverfang22** [comment]
I got the DXR6 Disruptor Rifle (sniper version) to disintegrate a stormtrooper NPC, however his body simply froze and disappeared with no disintegration effects played.
