### ISSUE TITLE
Grenades apply knockback

### ISSUE THREAD

**Issue by eezstreet** [JKGDevs/JediKnightGalaxies#251]
Before, grenades did not apply knockback because their damage type ("explosion"). But this yields a question: should we have a generic "explosion" damage type, which does not have knockback? Bearing in mind here, that only one damage type can be applied to the firing mode.

**Comment by DarthFutuza** [comment]
Sure, I would call it area_damage though not explosion, since you expect grenades to have knockback when they're explosion based.  eg: Poison grenades should not have knockback, but plasma grenades should.

**Comment by eezstreet** [comment]
Just needs .wpn changes to implement it now.

**Comment by Silverfang22** [comment]
Will do Soon™

**Comment by eezstreet** [comment]
Fixed this for most grenades. Some grenades still do have knockback. Just note that only damage areas can have the no knockback flag applied. We can tweak this for other grenades later.
