### ISSUE TITLE
jkg_allowDebuffKills incomplete with new debuff system

### ISSUE THREAD

**Issue by DarthFutuza** [JKGDevs/JediKnightGalaxies#252]
Should jkg_allowDebuffKills have a provision for if it is set to 2, meaning that only debuffs which indicate in buffs.json that they are "deadly" (eg: poison, fire and freeze all should, while bleed and stun should not be "deadly") will allow you to get kills from?

**Comment by Silverfang22** [comment]
It should probably work like this:
0 - debuffs can never kill
1 - debuffs can kill except when not "deadly" i.e. bleed/stun/etc.
2 - debuffs can always kill regardless of "deadliness"

should we call it "deadly" or "canKill"?

**Comment by DarthFutuza** [comment]
That'd work better, makes more sense.  Although I don't think stun does any damage as a debuff (so it would never be deadly).

**Comment by DarthFutuza** [comment]
Partially fixed in c877ec1 , 1 is not yet a feature (behaves like 2 right now).  Will probably save this for after scrimmage me thinks.  I restructured some code to make it easier to implement.
