### ISSUE TITLE
Armor items from the same modelGroup can't use alternate skins

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#256]
helmet_stormtrooper_rusty appears to use the default skin instead of the reddirt skin, likewise with rebel helmet variations.

the function of using different skins does work though, as seen with the coat_heavy armor item.

**Comment by eezstreet** [comment]
That's sort of the point. modelGroup is for binding all armors of the same model/skin combination to the same GHOUL2 instance and therefore optimizing the renderer. If you use a different model/skin combination in the same modelGroup then it will cause issues like this.

Not a bug; it's functioning how it should be. Use a different modelGroup for the rusty skin.
