### ISSUE TITLE
Stuns are OP

### ISSUE THREAD

**Issue by DarthFutuza** [JKGDevs/JediKnightGalaxies#261]
Stuns last way too long.  You can actually pull off a stun, switch firing modes and then finish them off before the stun buff finishes.  Need to reduce how long they last by a lot.  The tactic feels very cheap and frustrating.

**Comment by eezstreet** [comment]
Just a note, this is actually tweakable via the .wpn file now. I think I set it to be 4 seconds for most weapons but it might've been 2 seconds before.

**Comment by eezstreet** [comment]
Reduced it to 2 seconds on most weapons again. Closing this. Reopen if it's a problem again.
