### ISSUE TITLE
Stun animation freezes

### ISSUE THREAD

**Issue by DarthFutuza** [JKGDevs/JediKnightGalaxies#264]
After being stunned animation (usually, every once in a while it won't happen) gets stuck into "stun" position (which looks a little silly).  The player can still move and function as normal after the stun debuff cools off, but the animation isn't appropriate.  (You can reset the animation by doing a kick, and probably other things).  Additionally this means that if you are killed while in this stuck animation no death animation is played and your body just stays standing in the air visible until the body is cleaned up.

**Comment by eezstreet** [comment]
Death animation is now no longer frozen on death.

**Comment by Silverfang22** [comment]
somewhat related: Armor animation is not frozen in the same manner as player animations when stunned.

**Comment by DarthFutuza** [comment]
Saw this happen with 1.3c playtest today, not fixed?  Going to try to reproduce on develop and report back here.

**Comment by DarthFutuza** [comment]
This is definitely still happening.  People killed with a stun will freeze and not get their death animation played.

**Comment by DarthFutuza** [comment]
Fixed this with eb63f32
