### ISSUE TITLE
Armor does not reduce damage taken

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#268]
To be clear, damage types are working, meaning blasters do more damage against armored targets and slugthrowers do less, but the damage reduction from armor is not being applied at all!

**Comment by DarthFutuza** [comment]
I'll look at it if I have time, eezstreet might beat me to it though.

**Comment by eezstreet** [comment]
It looks like this is an error of the .arm files. The EHP field was renamed to "armor" but none of the armor files got changed to match this.

**Comment by DarthFutuza** [comment]
Ultimate derp right there.  @Silverfang22 commit those files :D

**Comment by Silverfang22** [comment]
Shoot me.
