### ISSUE TITLE
Fire Debuff does not interact with shields properly

### ISSUE THREAD

**Issue by DarthFutuza** [JKGDevs/JediKnightGalaxies#270]
I'm not sure exactly what it SHOULD do, but it should not do one tick of damage to shield on first apply and then burn hp with shield.  It should either
a) Do damage to shield until shield is depleted or debuff runs out/is cancelled
b) Be nullified by shields entirely as long as there is a charge

**Comment by Silverfang22** [comment]
Fire means of damage should damage shields instead of ignoring them, as long as you have shields up you cannot gain the fire debuff.

**Comment by DarthFutuza** [comment]
Sounds good.

**Comment by eezstreet** [comment]
So we need some way of detecting whether shields are up, before applying the debuff, if I understand correctly?

**Comment by DarthFutuza** [comment]
Aye.  That or just immediately put fire out if you have shield on.

**Comment by Silverfang22** [comment]
It shouldn't immediately put the fire out if you have a shield on, in fact if you get lit on fire, then gain a shield it should damage your health but not the shield as it does now (?)

**Comment by eezstreet** [comment]
I think it's fine as it is now, after playtesting.

**Comment by DarthFutuza** [comment]
Wait wut?  It just flat out ignores shields though...
