### ISSUE TITLE
L8 Striker Balance

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#275]
Costs too little, probably does too much damage for its current fire rate (nerf one or the other, maybe both).

**Comment by DarthFutuza** [comment]
I'd like to have more pistol options when first spawning, so I'm in favor of nerfing  Or maybe make a higher powered variant that costs more?  And nerf the normal one?

**Comment by eezstreet** [comment]
I think most pistols cost too much, considering that the DC-15a is like 1500 credits. 

Most repeaters should cost more than 2000 credits and concussion rifles should cost more as well.

**Comment by DarthFutuza** [comment]
With its current price and its current rate of fire I think its fine compared to other pistols.  It still needs textures though.  I'm going to close this one.  If you still think its unbalanced feel free to reopen Silverfang.
