### ISSUE TITLE
Detonator Consumables delete themselves

### ISSUE THREAD

**Issue by DarthFutuza** [JKGDevs/JediKnightGalaxies#282]
Since detonator type items were added as consumables, after placing your last one the item is removed from your inventory and you can't detonate. Eg sequencer

Possible Fixes:
*Don't remove until detonation is pressed, just set ammo count to 0?
*Two seperate stacks? A detonator button and detonator charges?
*Don't treat as consumable, make it a weapon with ammo?

**Comment by Silverfang22** [comment]
Detonator weapon with mine consumables as ammo. Maybe make a special case where it gives you a detonator with mine consumables if you don't have one in inventory

**Comment by Silverfang22** [comment]
Also we're starting to touch the territory of consumables that use consumables...

A while back there was discussion of mines that could use grenades as their payload

**Comment by DarthFutuza** [comment]
![shot2024-04-23_01-37-44](https://github.com/JKGDevs/JediKnightGalaxies/assets/4450419/6cab7ac7-23d2-4f40-825f-36078ccca0e9)

Simple temp fix, prevent user from using the last charge! Okay we need to do something more clever, but here's a placeholder fix for now.  See 609fc16.
