### ISSUE TITLE
Ammo Costs

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#290]
Ammo probably costs way too much money, it is far more cost efficient to sell the old gun and purchase a new one in the shop (if the same gun is available) which comes with a decent amount of ammo. Purchasing max ammo can result in costing more credits than the most expensive weapons in the game.

**Comment by DarthFutuza** [comment]
It depends on the gun, but yeah a lot of ammo needs a balance pass on pricing.

**Comment by Silverfang22** [comment]
Yeah I just noticed that, some prices are reasonable, some far exceed the cost of the gun itself.

**Comment by DarthFutuza** [comment]
Addressed in 8528c82 and b140943 if there are still issues, please feel free to also edit.
