### ISSUE TITLE
Broken or Missing Shader for LJ-70 Beam hit effect

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#294]
![shot2019-04-03_19-01-39](https://user-images.githubusercontent.com/5751886/55522635-fd5be880-5642-11e9-9d58-52b8524ee559.jpg)

**Comment by DarthFutuza** [comment]
I'll double check, but I don't think this is happening on my copy, you might be missing an asset.

**Comment by DarthFutuza** [comment]
Confirmed it happens on mine, does it happen on an old build?  Maybe we still have the asset somewhere.

**Comment by Silverfang22** [comment]
Fixed with 462436e79a7951c614480414a50908c28b6fd52d

Someone removed Stargate stuff from the WaterFX shader
