### ISSUE TITLE
Can't use jetpacks when stamina is too low

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#298]
Possible solutions:
Allow jetpack activation from ACI
Allow short, non-spammable, hops that are just long enough to activate a jetpack reliably

**Comment by DarthFutuza** [comment]
I kinda disagree, because I think it helps balance them out.  You can also just walk off an edge to activate which includes most maps.

**Comment by Silverfang22** [comment]
Making something frustrating to use isn't a good way to balance something in my opinion
