### ISSUE TITLE
More traveling vendors

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#302]
Add in some of the new vendors that Futuza created as traveling vendors

**Comment by DarthFutuza** [comment]
I'm thinking these work better as being placed in map bases, anyone want to go through all the maps and entity hack new vendors into the bases?

**Comment by DarthFutuza** [comment]
Alternatively, you could use Lua to make npc spawners for these which is probably a better solution than having to redistribute the maps.

**Comment by DarthFutuza** [comment]
Yeah this is a thing now.
