### ISSUE TITLE
Multiple weapons use incorrect reload animation

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#303]
Many weapons use the opposite reload animation from what they should (e.g. BOTH_RIFLERELOADL instead of BOTH_RIFLERELOADR).

**Comment by Silverfang22** [comment]
So I guess the "R" and "L" don't refer to which side the magazine is on, it refers to which hand holds the gun while you reload it >.>

Unfortunately every .wpn file will need to be gone through one at a time.

**Comment by DarthFutuza** [comment]
Oh dang that's annoying, might be able to simplify it with a script or regex.

**Comment by Silverfang22** [comment]
No, because not every weapon uses the wrong animation :P

**Comment by Silverfang22** [comment]
Fixed with 5204511028a332a58c166eb29db574fca46086f9
