### ISSUE TITLE
New grenade warning beeps

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#309]
Different types of grenades should have different warning beeps, especially bacta grenades since you're not supposed to run away from them.

**Comment by DarthFutuza** [comment]
sound\weapons\grenadeloop.wav is the current sound, need to add an override field for the .wpn files and some code to handle it

**Comment by Silverfang22** [comment]
Discovered yesterday that there is an override field for this (thermal detonators use a different sound), we just need a new sound to go with bacta grenades.

**Comment by DarthFutuza** [comment]
I have created 3 new sample sounds, will include one of them with the final assets.
