### ISSUE TITLE
Navigation Menu opens when scrolling down

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#310]
Navigation menu should open when scrolling back to the top of the web page on both mobile and desktop versions.

Possibly always display navigation menu if you're near the top of the web page, hide it once you scroll past a certain point?

**Comment by DarthFutuza** [comment]
So there's actually a separate issue tracker for different repos.  The webpage one is over here: https://github.com/JKGDevs/jkgalaxies.net/issues

New issue: https://github.com/JKGDevs/jkgalaxies.net/issues/2
