### ISSUE TITLE
Trip Mines Not Triggering Each Other

### ISSUE THREAD

**Issue by DarthFutuza** [JKGDevs/JediKnightGalaxies#317]
Trip Mines (and probably other objects/explosives), don't seem to be capable of damaging each other, so they don't set off chain reactions at the moment.  I recently fixed ( 480180b ) the issue of them not being able to take damage from blaster/missile based weapons, I suspect that due to eezstreet's rewrite of how damage works via calling the debuff function this has prevented them from also interacting via damage areas.

**Comment by Silverfang22** [comment]
Grenades will no longer detonate tripmines either, but launchers and blasters with splash damage will. Could this be related to the fact that they are consumables for some strange reason?

**Comment by DarthFutuza** [comment]
> 
> 
> Grenades will no longer detonate tripmines either, but launchers and blasters with splash damage will. Could this be related to the fact that they are consumables for some strange reason?

I think I know what's happening, I believe its due to the way the damage for these weapons is being called.  Some are using JKG_DirectDamage when they should be using JKG_DoDamage instead.  I'll see if I can fix that tomorrow.

**Comment by xycaleth** [comment]
I think this line is the issue:
https://github.com/JKGDevs/JediKnightGalaxies/blob/master/codemp/game/jkg_damageareas.cpp#L560

The grenades do damage over time with the area damage stuff, and this function only damages players and not other entities.

**Comment by xycaleth** [comment]
Actually the problem seems to be worse than that... various damage functions assume it's only going to damage players and ignore other entities, with various bits of code here and there to workaround previous problems 😬

**Comment by xycaleth** [comment]
Should be fixed in a30f192
