### ISSUE TITLE
Stun debuff not cleared on death

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#325]
Dying from a stun blast will result in not being able to move on spawn, /kill does clear this.

**Comment by DarthFutuza** [comment]
I've found that this doesn't seem to always be the case, still investigating.

**Comment by DarthFutuza** [comment]
This might be fixed with that last commit, but needs testing as the original issue was not persistent.

**Comment by DarthFutuza** [comment]
I believe this is now fixed completely with the addition of d3186e8 .  Reopen if issue persists.
