### ISSUE TITLE
Overheating bad interactions with charged and burst weapons

### ISSUE THREAD

**Issue by Silverfang22** [JKGDevs/JediKnightGalaxies#347]
Firing a burst weapon that overheats in the middle of the burst will no longer fire off the burst, but will only fire as many projectiles as would finish the burst. For example, firing an EE-3 at high heat where 1 shot makes you overheat will result in only 2 shots being fired once you shoot again.

Similar to an issue fixed with burst weapons, firing a charge weapon that results in overheat will fire the charged shot after the overheat finishes such as a proton carbine alternate fire.

**Comment by DarthFutuza** [comment]
@Silverfang22 this seems like expected behavior to me, are you wanting it to flush the current burst round instead?

**Comment by DarthFutuza** [comment]
Fixed with 491aac92
