### ISSUE TITLE
Respawning

### ISSUE THREAD

**Issue by gerbilOFdoom** [JKGDevs/JediKnightGalaxies#35]
Presently, no "click to respawn" or "respawning in x" timer is shown initially upon death. A click has to be made first for the text to show up. This is strange and unintuitive.

**Comment by Silverfang22** [comment]
Timer displays after screen fully fades to black, closing.

**Comment by DarthFutuza** [comment]
I still think it's confusing personally, I think players want instant feedback.  Also weren't deaths supposed to show everything in black and white while dead?
