### ISSUE TITLE
Gametypes not working correctly on servers

### ISSUE THREAD

**Issue by Pande** [JKGDevs/JediKnightGalaxies#36]
If you start a dedicated server with gametype 'tffa' it acts like FFA, but 4 apparently works fine. (4 = tffa)

Could be from when I rearranged the gametypes, see my commits:

https://github.com/JKGDevs/JediKnightGalaxies/commit/32b815fcb3da31cdeeb53738b71c9d6517d0f1d6
https://github.com/JKGDevs/JediKnightGalaxies/commit/50ee728ae7dc9dab9ce27a965af832a4b42fadd8

Dedicated server only.

**Comment by eezstreet** [comment]
Unable to reproduce.
