### ISSUE TITLE
Status Effects

### ISSUE THREAD

**Issue by gerbilOFdoom** [JKGDevs/JediKnightGalaxies#66]
A variable for status effects should be added to the entity/player state.

From this point, either the game engine should handle status effects configurable via cvar or status effect handling should be handled via GLUA.

In terms of time-to-viable, setting up the status effects directly in C++ would be faster. On the other hand, setting status effects up to operate in GLUA means that server operators can make changes to how status effects work on the fly. 

If the GLUA route is chosen then some sort of onhit callback might be necessary for weapons/force so that the appropriate action can be taken even if the action is not a status effect.

**Comment by DarthFutuza** [comment]
This is essentially irrelevant now with the addition of the buff system and means of damage systems which are mainly controlled through json data.  Closing this out for now as its a very old issue that is no longer really relevant.
